---

- name: 'Install a list of packages'
  apt:
    update_cache: true
    pkg:
      - 'tmux'
      - 'python3-apt'
      - 'python3-docker'
      - 'python3-pip'
      - 'vim'
      - 'nano'
      - 'git'
      - 'docker.io'
      - 'docker-compose'
      - 'fail2ban'
      - 'wget'
      - 'curl'
      - 'zabbix-agent'
      - 'pass'
      - 'gnupg2'
      - 'htop'
      - 'parted'
